---
galaxy_info:
  author: OpenShift SRE
  description: Create a project
  company: Red Hat, Inc
  license: ASL 2.0
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 7
dependencies:
- role: tools_roles/lib_oa_openshift
